language: ruby
sudo: false
cache: bundler
before_script: bundle install --jobs=3 --retry=3

rvm:
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/Gemfile.rails-5-2-stable
  - gemfiles/Gemfile.rails-6-0-stable
